### ISSUE TITLE
Clicking on file from "Recent" tab opens in default browser rather than in app

### ISSUE THREAD

**Issue by mcphail** [sirredbeard/unofficial-webapp-office#12] opened 2020-01-04 18:10 UTC
Ubuntu Mate 19.10 with Firefox as the default browser.

Open "Word" from menu. Click on first Word document under the "Recent" tab (file stored on OneDrive). File opens in new window in Firefox rather than in app.

```
$ snap --version
snap    2.42.5
snapd   2.42.5
series  16
ubuntu  19.10
kernel  5.3.0-24-generic

$ snap info unofficial-webapp-office 
name:      unofficial-webapp-office
summary:   Unofficial web app wrapper for Office 365 web apps
publisher: Hayden Barnes (haydenb)
contact:   hayden.barnes@canonical.com
license:   unset
description: |
  A set of web app wrappers, based on QtWebEngine, for the following
  websites:
  
  - Outlook
  - Word
  - Excel
  - PowerPoint
  - OneDrive
  - OneNote
  
  These are links to the Office 365 web apps embedded in a minimalist web
  browser.
  
  This snap is not supported by or endorsed by Microsoft, Inc.
  
  Office 365, OneNote, OneDrive, Outlook, Excel, PowerPoint, and Microsoft
  are trademarks or registered trademarks of Microsoft, Inc.
  
  Qt is a registered trademark of The Qt Company Ltd. and its subsidiaries.
  
  This application is forked from icloud-for-linux and is licensed under the
  GPL 3.0.
commands:
  - unofficial-webapp-office.excel
  - unofficial-webapp-office.onedrive
  - unofficial-webapp-office.onenote
  - unofficial-webapp-office.outlook
  - unofficial-webapp-office.powerpoint
  - unofficial-webapp-office.word
snap-id:      wQO3kg43noi8ZtLchLnWd5072mC116bP
tracking:     stable
refresh-date: today at 18:01 GMT
channels:
  stable:    0.2 2019-12-22 (28) 115MB -
  candidate: ↑                         
  beta:      ↑                         
  edge:      ↑                         
installed:   0.2            (28) 115MB -
```

**Comment by mijorus** [comment] 2020-01-06 18:53
same

**Comment by sirredbeard** [comment] 2020-01-14 20:01
Can you isolate the URL it is linking to there? Either by capturing the link opened in Firefox or inspecting the code in your browser? It may be linking to a domain name I don't have listed as an Office domain. I can add it if that's the case.

**Comment by mcphail** [comment] 2020-01-14 20:08
Hi

the link opens as `https://1drv.ms/w/blah` then rapidly de-minifies to `https://onedrive.live.com/edit.aspx?resid=blah&etc`. I can PM you the actual links if it helps.

**Comment by sirredbeard** [comment] 2020-01-14 20:22
I pushed a fix in this commit https://github.com/sirredbeard/unofficial-webapp-office/commit/18d0904819ee80e4b3a6692bdc2bd775d07877f6

It has been built and pushed out.

Please exit everything, run snap refresh, try again, and report back.

**Comment by sirredbeard** [comment] 2020-01-14 20:55
Confirmed fixed.

**Closed as completed by sirredbeard** 2020-01-14 20:55 UTC
Labels: bug

**Comment by mcphail** [comment] 2020-01-14 20:56
That's great, Hayden. Documents seem to open in app, now.

They do, however, open in a new window of the app. Is that intended behaviour? I'd expected them to open in the same window.

(As an aside, the `snap refresh` seems to have killed the menu entries for all the office apps on my Mate install. I had to open Word from the terminal. has the .desktop file changed?)

**Comment by sirredbeard** [comment] 2020-01-14 21:07
That is the intended behavior for all links right now.

Changes were made to the desktop files several builds ago to fix keyword and categories but you should have already had those updates. 

Sometimes snapd regenerates the desktop files and then your desktop has to detect, there can be a lag.

**Comment by mcphail** [comment] 2020-01-14 21:11
That's super. Thanks so much! I owe you $BEVERAGE_OF_YOUR_CHOICE for making this :)
